class datos:
    def __init__(self):
            self.nombres=[
            "Juan",
            "María",
            "Carlos",
            "Ana",
            "Pedro",
            "Laura",
            "José",
            "Sofía",
            "Miguel",
            "Luis",
            "Carmen",
            "Isabel",
            "Diego",
            "Lucía",
            "Fernando",
            "Elena",
            "Manuel",
            "Patricia",
            "Roberto",
            "Silvia",
            "Javier",
            "Raquel",
            "Andrés",
            "Pilar",
            "David",
            "Rocío",
            "Gonzalo",
            "Natalia",
            "Alejandro",
            "Eva",
            "Rafael",
            "Beatriz",
            "Óscar",
            "Adriana",
            "Federico",
            "Cristina",
            "Guillermo",
            "Victoria",
            "Francisco",
            "Olga",
            "Ángel",
            "Cecilia",
            "Ricardo",
            "Marta",
            "Luisa",
            "Lorenzo",
            "Clara",
            "Fabián",
            "Irene",
            "Alberto",
            "Susana",
            "Simón",
            "Elsa",
            "Joaquín",
            "Valentina",
            "Sebastián",
            "Alicia",
            "Emilio",
            "Mónica",
            "Arturo",
            "Rosa",
            "Ignacio",
            "Lourdes",
            "Gustavo",
            "Ángela",
            "Roberto",
            "Camila",
            "Hugo",
            "Nerea",
            "Ramón",
            "Verónica",
            "Pablo",
            "Lidia",
            "Álvaro",
            "Daniela",
            "Enrique",
            "Miriam",
            "Samuel",
            "Nuria",
            "Víctor",
            "Judith",
            "Félix",
            "Carolina",
            "Raul",
            "Inés",
            "Omar",
            "Teresa",
            "Joaquín",
            "Celia",
            "Iván",
            "Clara",
            "Eduardo",
            "Paula",
            "Antonio",
            "Sara",
            "Alberto",
            "Vanesa",
            "Álex",
            "Gemma",
            "Julio",
            "Mireia",
            "Felipe",
            "Ruth",
            "Marcos",
            "Sonia",
            "Nacho",
            "Esther",
        ]
            self.apellidos= [
            "González", "Rodríguez", "Gómez", "Fernández", "López", "Díaz", "Martínez", "Pérez", "García", "Sánchez",
            "Romero", "Serrano", "Muñoz", "Hernández", "Jiménez", "Lara", "Torres", "Ortega", "Castillo", "Ruiz",
            "Rubio", "Navarro", "Molina", "Delgado", "Alvarez", "Ramírez", "Vargas", "Ramos", "Moreno", "Márquez",
            "Blanco", "Cano", "Suárez", "Mendoza", "Herrera", "Medina", "Aguilar", "Castro", "Jiménez", "Vega",
            "Florez", "Vázquez", "Carmona", "Cruz", "Giménez", "Iglesias", "Arias", "Gutiérrez", "Núñez", "Reyes",
            "Morales", "Peralta", "Soto", "Aguirre", "Silva", "Bravo", "Rojas", "Estrada", "Fuentes", "Nieves",
            "Cabrera", "Guerrero", "Rosales", "León", "Salgado", "Cervantes", "Santos", "Gallardo", "Reyes", "Campos",
            "Pacheco", "Padilla", "Calderón", "Guerrero", "Ávila", "Peña", "Guillén", "Guerra", "Orozco", "Benítez",
            "Cárdenas", "Escobar", "Montes", "Olivares", "Paredes", "Lugo", "Castañeda", "Carrillo", "López", "Pinto",
            "Maldonado", "Arroyo", "Sosa", "Valencia", "Salinas", "Osorio", "Nieto", "Bermúdez", "Quintero", "Guzmán",
            "Olivera", "Jaimes", "Mata", "Leyva", "Zamora", "Amaya", "Parra", "Camacho", "Téllez"
        ]
            self.mensajes = [':)' , ':(' , ':D' , ':P' , ';)' , ":'(" , ':O' , ':|' , ':/' , ':*' , '<3' , '-_-', ':v' , '0_0' , '-_-*' , '>_<' ,
              '^_^' , '-.-' , 'o.O' , 'O.o' , '-_-;' , '-_-zzz' , ':3' , '-_-' , '8-)' , '8-|' , ':O_o:' , '>:O' , ':-/' , ':-*' ,
             ':3' , ':-)' , ':-D' , ';-)' , ';(' , ':-P' , ':-|' , ":'(" , ':-O' , ':-|' , ':-/' , ':-*' , ':v' , ':/' , ':O' ,
             '8-|' , ':-)' , ':*' , '>_<' , ":'(" , ':O' , '-_-', ':D' , '-_-;' , ':3' , ';)' , ':/' , '-_-*' , '^_^' , '0_0' ,
             '-.-' , ':|' , ':O' , ':v' , ':-D' , ":'(" , ':P' , ':O' , ':*' , ':/' , ';)' , '8-|' , ':D' , ':*' , ':/' , '>_<' ,
             '^_^' , ':3' , ':-|' , ':-P' , ':-)' , ":'(" , ';-)', ":-)", ";-)", ":-D", ":-P", ":-(", ":-O", ":-|", ":-*", "<3", "^_^",
             "O:-)", ">:O", ":-/", ":'(", ">:(", ":-[", ":-]", "<('.'<)", "(>'.')>",
             "(^^)/", "(..)", "(¬‿¬)", "(ᵔᴥᵔ)", "(••)", "(¬¬)", "(><)", "(;;)",
             "(-_-)", "(o_o)", "(0_0)", "(>.<)", "(≧◡≦)", "(¬▂¬)", "(ಠ_ಠ)", "(◕‿◕)",
             "(¬‿¬)", "(◕‿-)", "(◠‿◠)", "(｡♥‿♥｡)", "(ʘ‿ʘ)", "(¬_¬)", "(´• ω •`)", "(¬‿¬)",
             "( ͡° ͜ʖ ͡°)", "(ง •_•)ง", "(ಠ‿↼)", "(¬‿¬)", "(づ｡◕‿‿◕｡)づ", "(☞ﾟ∀ﾟ)☞", "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
             "(∩︵∩)", "ᕦ(ò_óˇ)ᕤ", "(ノಠ益ಠ)ノ彡┻━┻", "(╯°□°）╯︵ ┻━┻", "┬─┬ノ(ಠ_ಠ)", "¯\(ツ)/¯", "(⌐■■)", "(☼☼)",
             "(⊙☉)", "(¬¬)ﾉ", "┌( ಠ_ಠ)┘", "(✿◠‿◠)", "(╥﹏╥)", "( ͡ᵔ ͜ʖ ͡ᵔ )", "(•_•)>⌐■-■", "(❍ᴥ❍ʋ)",
             "(◕‿-)", "˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚", "(︺︹︺)", "(¬‿¬)", "(•_•)⌐■-■", "(¬‿¬)ﾉ", "(¬‿¬)凸",
             "( ͡°Ĺ̯ ͡° )", "(¬¬)ﾉ", "٩(͡๏̯͡๏)۶", "(••)>⌐■-■", "(¬¬)ﾉ", "(¬‿¬)凸", "༼ つ ◕◕ ༽つ", "(¬‿¬)", "(¬_¬)"]